version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
        target-branch: "qa"

  # Maintain dependencies for Docker
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
        target-branch: "qa"

  # Maintain dependencies for npm and yarn
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
        target-branch: "qa"
