export const WALLET_LEDGER = 'WALLET_LEDGER';
export const WALLET_ELECTRUM = 'WALLET_ELECTRUM';
export const WALLET_TREZOR = 'WALLET_TREZOR';
export const WALLET_RWALLET = 'WALLET_RWALLET';
export const WALLET_DEFIANT = 'WALLET_DEFIANT';
